---
title: "MP_data_processing_model"
author: "Matt Pitz, Nan Li, Ada Guan"
date: '2022-04-03'
output: html_document
---

```{r load packages and set options, include=FALSE}
library(tidyverse) 
library(magrittr)
library(knitr)
if (!require("patchwork")) install.packages('patchwork')
if (!require("moments")) install.packages('moments')
if (!require("arrow")) install.packages('arrow')
library(patchwork)
library(moments)
library(arrow)
library(readr)
library(ggplot2)
library(stargazer)
library(lmtest)
library(sandwich)
#tinytex::install_tinytex()
theme_set(theme_bw())

options(tinytex.verbose = TRUE)
knitr::opts_chunk$set(echo=FALSE, message=FALSE)

notebooks_path <- getwd()
root_path <- dirname(notebooks_path)
data_path <- file.path(root_path,"src","data","raw")
```

```{r read in clean data}
post_1990_merge <- read_parquet(file = file.path(data_path, "post_1990_clean_data"))
```

```{r, scatter plot}
post_1990_raw_histogram <- post_1990_merge %>%
filter(box_office != "" & budget != "") %>%
  ggplot() + 
  aes(x = clean_budget_real, y = clean_box_office_real, color = genre_primary) +
  geom_point() +
    labs(title ='Box Office Earning Based On Budget',
       x ='Budget (Million $)',
       y ='Box Office (Million $)')

post_1990_raw_histogram
```

###Models

Model 1: Baseline model (only including one independent variable):

$$
\text{log(Box office)} = \beta_0 + \beta_1*\text{log(Budget)}
$$

Model 2: Model including additional independent variables of interest:
$$
\text{log(Box office)} = \beta_0 + \beta_1*\text{log(Budget)} + \beta_2*\text{duration} + \beta_3*\text{maturity_rating} + \beta_4*\text{genre_primary}
$$

Model 3: Model including more independent variables of interest (meta_critic_rating and thankxmas):
$$
\text{log(Box office)} = \beta_0 + \beta_1*\text{log(Budget)} + \beta_2*\text{duration} + \beta_3*\text{maturity_rating} + \beta_4*\text{genre_primary} + \beta_5*\text{meta_critic_rating} + \beta_6*\text{thanksxmas}
$$

Model 4: Model including additional binary variables (summer and received_award):
$$
\text{log(Box office)} = \beta_0 + \beta_1*\text{log(Budget)} + \beta_2*\text{duration} + \beta_3*\text{maturity_rating} + \beta_4*\text{genre_primary} + \beta_5*\text{meta_critic_rating} + \beta_6*\text{thanksxmas} + \beta_7*\text{summer} + \beta_8*\text{award}
$$

```{r select columns of interests}
post_1990_raw <- post_1990_merge[c('title','maturity_rating','duration_minutes',
                                   'clean_box_office_real','clean_budget_real',
                                   'genre_primary','rotten_tomatoes_rating',
         'release_year','release_month','summer','thanksxmas','received_award','meta_critic_rating')]
post_1990 <- na.omit(post_1990_raw)

post_1990_filtered <- post_1990 %>%
  #remove extreme outliers as a result of EDA, remove values between 0 and 1
  filter(clean_box_office_real < 1990 & clean_box_office_real >= 1.0 & clean_budget_real >=1.0 & clean_budget_real <350)
post_1990_filtered <- post_1990_filtered %>% 
  mutate(
    box_office_log = log(clean_box_office_real), 
    budget_log = log(clean_budget_real)
  )
```
```{r, echo=FALSE, warning=FALSE, message=FALSE, comment=NA}
if (!require("stargazer")) install.packages('stargazer')
if (!require("sandwich")) install.packages('sandwich')
if (!require("lmtest")) install.packages('lmtest')
#source('../src/data/get_robust_se.R')
model_1 = lm(data=post_1990_filtered, box_office_log ~ budget_log)
model_2 = lm(data=post_1990_filtered, box_office_log ~ budget_log + duration_minutes +
               maturity_rating + genre_primary)
model_3 = lm(data=post_1990_filtered, box_office_log ~ budget_log + duration_minutes +
             maturity_rating + genre_primary + meta_critic_rating + thanksxmas)
#Additional binary variables (summer and received_award)
model_4 = lm(data=post_1990_filtered, box_office_log ~ budget_log + duration_minutes +
             maturity_rating + genre_primary + meta_critic_rating + thanksxmas + summer + 
               received_award)
model_5 = lm(data=post_1990_filtered, box_office_log ~ budget_log + duration_minutes +
             maturity_rating + genre_primary + meta_critic_rating + release_month)
model_6 = lm(data=post_1990_filtered, box_office_log ~ budget_log + duration_minutes +
             maturity_rating + genre_primary + meta_critic_rating + summer)
# Testing for release year
model_7 = lm(data=post_1990_filtered, box_office_log ~ budget_log + duration_minutes +
             maturity_rating + genre_primary + meta_critic_rating + thanksxmas + release_year)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE, comment=NA}

se.model_1 = coeftest(model_1, vcov = vcovHC)[ , "Std. Error"]
se.model_2 = coeftest(model_2, vcov = vcovHC)[ , "Std. Error"]
se.model_3 = coeftest(model_3, vcov = vcovHC)[ , "Std. Error"]
se.model_4 = coeftest(model_4, vcov = vcovHC)[ , "Std. Error"]
se.model_5 = coeftest(model_5, vcov = vcovHC)[ , "Std. Error"]
se.model_6 = coeftest(model_6, vcov = vcovHC)[ , "Std. Error"]
se.model_7 = coeftest(model_7, vcov = vcovHC)[ , "Std. Error"]

model_a_table <- stargazer(model_1, model_2, model_3, model_4, model_5, model_6, model_7, type = "text",
          header=FALSE, no.space=TRUE, column.sep.width = "3pt",
          star.cutoffs = c(0.05, 0.01, 0.001), title = "Summary for models 1 to 7")
```
```{r test models genre_primary, duration_minutes, maturity_rating, meta_critic_rating and release_month}
# model_test_1 = lm(data=post_1990_filtered, box_office_log ~ budget_log + genre_primary)
# model_test_2 = lm(data=post_1990_filtered, box_office_log ~ budget_log + genre_primary + duration_minutes)
# model_test_3 = lm(data=post_1990_filtered, box_office_log ~ budget_log + genre_primary + duration_minutes + maturity_rating)
# model_test_4 = lm(data=post_1990_filtered, box_office_log ~ budget_log + genre_primary + duration_minutes + maturity_rating + meta_critic_rating)
# model_test_5 = lm(data=post_1990_filtered, box_office_log ~ budget_log + genre_primary + duration_minutes + maturity_rating + meta_critic_rating + release_month)
# 
# anova(model_test_1, model_test_2, test = 'F')
# anova(model_test_2, model_test_3, test = 'F')
# anova(model_test_3, model_test_4, test = 'F')
# anova(model_test_4, model_test_5, test = 'F')
```

```{r f-test for model_1, model_2 and model_3}
#A F test was conducted. Assumptions of F test: 1) the population must be 
# normally distributed and 2) the samples must be independent events. 
print("F test - Model 1 & Model 2")
anova(model_1, model_2, test = 'F')
# The p-value is less than 0.05 thus we can reject the null hypothesis, the 
# additional parameter duration_minutes, maturity_rating, and genre_primary that 
# were estimated in `model_2` makes this second model more fully represent the 
# true population.
print("F test - Model 2 & Model 3")
anova(model_2, model_3, test = 'F')
# Between model_2 and model_3 the additional covariate meta_critic_rating 
# and thanksxmas in model_3 have explanatory power and improves the fit 
# of the model. The null hypothesis is that model_2 model_3 have equal residual 
# sum of squares. If the probability (p-value) of observing F-value that is at 
# least as large as the F-value that the study got (5.615) is lower than 0.05, 
# then we can reject the null hypothesis. We can conclude by rejecting our null
# hypothesis since the p-value is less than 0.05 in this case. Model 3
# with additional covariates have explanatory power (is able to explain
# the variance in the dependent variable better than model 1 and 2) and are
# improving the model performance.
print("F test - Model 3 & Model 4")
anova(model_3, model_4, test = 'F')
# Failed to reject null hypothesis, p-value greater than 0.05. The binary
# covariates in model_4, summer and received_award do not have additional 
# explanatory power and does not improve the performance of the model.
```
```{r model comparison between release_month, summer, thanksxmax and release year}
print("F test - Model 3 & Model 5")
anova(model_3, model_5, test = 'F')
# P-value greater than 0.05, reject null hypothesis, model_5 with release_month
# does not improve the performance of the model.
print("F test - Model 3 & Model 6")
anova(model_3, model_6, test = 'F')
print("F test - Model 3 & Model 7")
anova(model_3, model_7, test = 'F')
# Release year does not have additional explanatory power compared to model 3. 
# Supporting evidence of not treating it as a time-series.
```
###Test CLM Assumptions
```{r model diagnostic plots}
plot(model_3, which=1)
plot(model_3, which=2)
plot(model_3, which=3)
plot(model_3, which=4)
plot(model_3, which=5)
```
```{r}
print("Coefficients with Heteroskedasticity-robust Standard Errors")
coeftest(model_3, vcovHC, type = "HC1")
```
```{r}
print("Formal Test of Heteroskedasticity")
bptest(model_3)
```
```{r}
print("Formal Test of Residual Normality")
set.seed(56423)
shapiro.test(sample(model_3$residuals, size = 5000,replace=TRUE))
# P-value < 0.05, indicates that we can reject the null hypothesis and that it 
# is normally distributed.
hist(model_3$residuals)
```
