---
title: "MP_data_processing"
author: "Matt Pitz"
date: '2022-04-01'
output: html_document
---

```{r load packages and set options, include=FALSE}
library(tidyverse) 
library(magrittr)
library(knitr)
library(patchwork)
library(moments)
if (!require("arrow")) install.packages('arrow')
library(readr)

theme_set(theme_bw())

options(tinytex.verbose = TRUE)
knitr::opts_chunk$set(echo=FALSE, message=FALSE)

notebooks_path <- getwd()
root_path <- dirname(notebooks_path)
data_path <- file.path(root_path,"data","raw")
```

```{r remove pre-1990 data, include=FALSE}
#only run this snippet once
 
  raw_file_path <- file.path(data_path,"movie_data_1950_2020.csv")
 
  raw_data <- read.csv(raw_file_path, header = TRUE, sep = ",")
 
  #convert release_year to numeric and drop all obs after 1990
  post_1990_raw <- raw_data %>%
    mutate(release_year = strtoi(release_year)) %>%
             filter(release_year >= 1990)
#save as parquet file
 write_parquet(post_1990_raw,
                sink = file.path(data_path, "post_1990_data"))
 
#browse_data <- post_1990_raw[1:50,]

```


```{r load parquet file, include=FALSE}
post_1990_raw <- read_parquet(file = file.path(data_path, "post_1990_data"))

```

```{r inital data cleaning , include=FALSE}
#count total obs (5605 obs)
ttl_count <- nrow(post_1990_raw)

#count obs without missing budget and box office that will be used in analysis
#597 obs >=1990
analysis_count <- post_1990_raw %>%
  filter(box_office != "" & budget != "") %>%
  nrow

#create clean budget and box office numbers
post_1990_raw <- post_1990_raw %>%
  mutate(
    clean_budget = ifelse(
      grepl("mil", budget, fixed=TRUE),
      parse_number(budget),
      parse_number(budget)/1000000
      ),
    clean_box_office = ifelse (
      grepl("mil", box_office, fixed=TRUE),
      parse_number(box_office),
      parse_number(box_office)/1000000
    )
  )

#correct for billions
post_1990_raw <- post_1990_raw %>%
  mutate(
    clean_box_office = ifelse(
      grepl("b", box_office, fixed=TRUE),
      parse_number(box_office)*1000,
      clean_box_office) 
  )
    

#create primary genre
post_1990_raw$genre_primary <- str_extract(post_1990_raw$genre, "[^/]+")

#combine related categories
post_1990_raw <- post_1990_raw %>%
  mutate(genre_primary = ifelse(
    genre_primary == "Adaptation" | genre_primary == "Docudrama" | genre_primary == "Hip hop" |
    genre_primary == "Historical drama" | genre_primary == "History" | genre_primary == "LGBT" |
    genre_primary == "Pornographic" | genre_primary == "Road",
    "Misc",
    genre_primary
    ),
    genre_primary = ifelse( 
     genre_primary == "Teen",
     "Family",
     genre_primary
    ),
    genre_primary = ifelse( 
     genre_primary == "Psychological thriller",
     "Thriller",
     genre_primary
    ),
    genre_primary = ifelse( 
     genre_primary == "Music",
     "Musical",
     genre_primary
    ),
    genre_primary = ifelse( 
     genre_primary == "Noir",
     "Crime",
     genre_primary
    ),
    genre_primary = ifelse( 
     genre_primary == "Action Thriller",
     "Action",
     genre_primary
    )
  )

#create release month
post_1990_raw$release_month <- str_extract(post_1990_raw$release_date,"(\\w+)") 
post_1990_raw <- post_1990_raw %>% 
  mutate(
    summer = ifelse(
    release_month == "May" |release_month == "June" | release_month == "July", 1,0) 
  )
post_1990_raw <- post_1990_raw %>% 
  mutate(
    thanksxmas = ifelse(
    release_month == "November" |release_month == "December" | release_month == "January",1,0)
  )


#convert duration into minutes
post_1990_raw <- post_1990_raw %>% 
  mutate(
    temp_hours = as.numeric(substr(duration,1,1))*60,
    temp_minutes = ifelse(
      grepl("m",duration),
      parse_number(str_extract(duration, "[0-9]{1,2}m")),
      0),
    duration_minutes = temp_hours + temp_minutes
  ) 

post_1990_raw <- post_1990_raw %>%
  select(-temp_hours, -temp_minutes)

#award flag
post_1990_raw <- post_1990_raw %>% 
  mutate(
    received_award = !is.na(awards)
  )

post_1990_raw$rotten_tomatoes_rating <- as.numeric(sub("%", "",post_1990_raw$rotten_tomatoes_rating,fixed=TRUE))/100

post_1990_raw$meta_critic_rating <- as.numeric(sub("%", "",post_1990_raw$meta_critic_rating,fixed=TRUE))/100

#browse_data <- post_1990_raw[1:30,]
```

```{r read in inflation}

#load in inflation
inflation_file_path <- file.path(data_path,"Inflation_Rates.csv")
 
inflation_data <- read.csv(inflation_file_path, header = TRUE, sep = ",")

colnames(inflation_data)[1] <- "release_year"

post_1990_merge <- merge(post_1990_raw,inflation_data ,by="release_year")

#convert dollar values to real
post_1990_merge$clean_budget_real <- post_1990_merge$clean_budget*post_1990_merge$Inflation_Rate
post_1990_merge$clean_box_office_real <- post_1990_merge$clean_box_office*post_1990_merge$Inflation_Rate

write_parquet(post_1990_merge,
               sink = file.path(data_path, "post_1990_clean_data"))

#browse_data2 <- post_1990_merge[1000:1030,]
```

